const { Router } = require("express");
const adminController = require("../../controller/admin/admin.controller");
const {
  documentModuleCreateRules,
  validate,
  publishDocumentModuleRules,
  trainingSimulationModuleCreateRules,
  publishTrainingSimulationModuleRules,
  testSimulationModuleCreateRules,
  publishTestSimulationModuleRules,
  sopModuleCreateRules,
  publishSopModuleRules,
  createCategoryRules,
  documentDraftViewRules,
  trainingSimulationDraftViewRules,
  testSimulationDraftViewRules,
  sopDraftViewRules,
  assignElementToRoleAndDepartmentRules,
  viewElementDraftActivityLogRules,
  testMCQModuleCreateRules,
  publishTestMCQModuleRules,
  testMCQModuleDraftViewRules,
  changeCategoryStatusRules,
  deleteCategoryRules,
  impactAnalysisRules,
  formModuleCreateRules,
  publishFormModuleRules,
  formDraftViewRules,
  createFormRules,
  viewFormRules,
  createCampaignRules,
  exportCampaignExcelRules,
  campaignListRules,
  revokeAssignedUsersFromElementRules,
  fetchAssignedDataForElementRules,
  createBulkTestMCQRules,
  documentModuleBulkCreateRules,
  hideUnhideModuleRules,
  flowModuleCreateRules,
  viewElementDraftActivityLogHistoryRules,
  sopFlowDraftViewRules,
  createRiskRules,
  updateRiskRules,
} = require("../../validators/admin/admin.validator");
const multer = require("multer");
const { apiAccess } = require("../../utils/middleware/checkUserAccess");
const {
  createDocumentModule,
  createSOPModule,
  sendDocumentForReview,
  createOrUpdateTemplateOrBlankDocument,
} = require("../../controller/reviewapprovecycle/element.controller");

exports.adminRoutes = Router()
  .post(
    "/MIZrIxByZj3PsO5",
    apiAccess.ProcessOwner(),
    documentModuleCreateRules(),
    validate,
    createDocumentModule
  )
  .post(
    "/IZrsO5MIxByZj3P",
    apiAccess.ProcessOwner(),
    documentModuleBulkCreateRules(),
    adminController.createBulkDocumentModule
  )
  .post(
    "/c8ws3tuvxZuYY8R",
    apiAccess.ProcessOwner(),
    publishDocumentModuleRules(),
    validate,
    adminController.publishDocumentModule
  )
  .post("/q5bSSpjTwR2SJaQ", adminController.listDocumentModule)
  .post(
    "/cqMSpln8DrEcx9w",
    documentDraftViewRules(),
    validate,
    adminController.viewDocumentModuleDraft
  )
  .post(
    "/whWe475xubBh21x",
    apiAccess.ProcessOwner(),
    documentDraftViewRules(),
    validate,
    adminController.deleteDocumentModule
  )
  .post(
    "/h21xw75xubBhWe4",
    apiAccess.EndUser(),
    documentDraftViewRules(),
    validate,
    adminController.updateDocumentStatus
  )
  .post(
    "/xuxwhWeh21475bB",
    apiAccess.ProcessOwner(),
    adminController.exportDocuments
  )
  .post(
    "/daHHQfkkvNuq7zR",
    apiAccess.ProcessOwner(),
    trainingSimulationModuleCreateRules(),
    validate,
    adminController.createTrainingSimulationModule
  )
  .post(
    "/bxQbbCR2rGOhhUq",
    apiAccess.ProcessOwner(),
    publishTrainingSimulationModuleRules(),
    validate,
    adminController.publishTrainingSimulationModule
  )
  .post("/0QiQx1NM7b1c6FP", adminController.listTrainingSimulationModule)
  .post(
    "/mwe0jz5IA3U5lVd",
    apiAccess.ProcessOwner(),
    trainingSimulationDraftViewRules(),
    validate,
    adminController.viewTrainingSimulationModuleDraft
  )
  .post(
    "/vCWBWxC05mUQfCr",
    apiAccess.ProcessOwner(),
    trainingSimulationDraftViewRules(),
    validate,
    adminController.deleteTrainingSimulationtModule
  )
  .post(
    "/xo0uYREJIJe91bR",
    apiAccess.ProcessOwner(),
    testSimulationModuleCreateRules(),
    validate,
    adminController.createTestSimulationModule
  )
  .post(
    "/spB4t1pugF9hnU3",
    apiAccess.ProcessOwner(),
    publishTestSimulationModuleRules(),
    validate,
    adminController.publishTestSimulationModule
  )
  .post("/pXoVGRSeA2lvubb", adminController.listTestSimulationModule)
  .post(
    "/bOPB54L4sCQsVz1",
    apiAccess.ProcessOwner(),
    testSimulationDraftViewRules(),
    validate,
    adminController.viewTestSimulationModuleDraft
  )
  .post(
    "/yZVbXWwa5Y7SNBO",
    apiAccess.ProcessOwner(),
    testSimulationDraftViewRules(),
    validate,
    adminController.deleteTestSimulationtModule
  )
  .post(
    "/dedg7DwY10Bpp4h",
    apiAccess.ProcessOwner(),
    multer().any(),
    sopModuleCreateRules(),
    validate,
    createSOPModule
  )
  .post(
    "/dgp4hde7DwY10Bp",
    apiAccess.ProcessOwner(),
    flowModuleCreateRules(),
    validate,
    adminController.createSOPFlowModule
  )
  .post(
    "/kDBfR5jCNpgS0zO",
    apiAccess.ProcessOwner(),
    publishSopModuleRules(),
    validate,
    adminController.publishSOPModule
  )
  .post(
    "/NpS0zOkDBfR5jCg",
    apiAccess.ProcessOwner(),
    publishSopModuleRules(),
    validate,
    adminController.publishSOPFlowModule
  )
  .post(
    "/vA9eTZ75GNq3fJQ",
    apiAccess.ProcessOwner(),
    adminController.listSOPModule
  )
  .post(
    "/dbIc6nabZUgJT4C",
    apiAccess.ProcessOwner(),
    sopDraftViewRules(),
    validate,
    adminController.viewSOPModuleDraft
  )
  .post(
    "/bIcJT4Cd6nabZUg",
    apiAccess.EndUser(),
    sopFlowDraftViewRules(),
    validate,
    adminController.viewSOPFlowModuleDraft
  )
  .post(
    "/rDNI5quBqsdDOAD",
    apiAccess.ProcessOwner(),
    sopDraftViewRules(),
    validate,
    adminController.deleteSOPModule
  )
  .post(
    "/DNdDOADrI5quBqs",
    apiAccess.ProcessOwner(),
    sopDraftViewRules(),
    validate,
    adminController.deleteSOPFlowModule
  )

  .post(
    "/ADdDrI5DNOquBqs",
    apiAccess.ProcessOwner(),
    adminController.getLatestSopData
  )

  .post(
    "/2QWFBKxfNOg8wgJ",
    apiAccess.ProcessOwner(),
    createBulkTestMCQRules(),
    validate,
    adminController.createBulkTestMCQ
  )
  .post(
    "/FBKxfNgJOg8w2QW",
    apiAccess.ProcessOwner(),
    testMCQModuleCreateRules(),
    validate,
    adminController.createTestMCQModule
  )
  .post(
    "/dDh8IMSEtqNNqSB",
    apiAccess.ProcessOwner(),
    publishTestMCQModuleRules(),
    validate,
    adminController.publishTestMCQModule
  )
  .post(
    "/j1nCksN95V7zcig",
    apiAccess.ProcessOwner(),
    adminController.listTestMCQModule
  )
  .post("/egdUxkEKokvoDnE", apiAccess.ProcessOwner(), adminController.listMCQs)
  .post(
    "/ojkNUIvYAWw3YZa",
    apiAccess.ProcessOwner(),
    testMCQModuleDraftViewRules(),
    validate,
    adminController.viewTestMCQModuleDraft
  )
  .post(
    "/pLAF1Pk7wV0TRnu",
    apiAccess.ProcessOwner(),
    testMCQModuleDraftViewRules(),
    validate,
    adminController.deleteTestMCQModule
  )
  .post(
    "/qxZrQraP39O6qmr",
    apiAccess.ProcessOwner(),
    createCategoryRules(),
    validate,
    adminController.createUpdateCategory
  )
  .post(
    "/PcerQraP39Ojqnt",
    apiAccess.ProcessOwner(),
    changeCategoryStatusRules(),
    validate,
    adminController.changeCategoryStatus
  )
  .post(
    "/OtbrQraP39Olpaz",
    apiAccess.ProcessOwner(),
    deleteCategoryRules(),
    validate,
    adminController.deleteCategory
  )
  .post(
    "/sl8vdNH9kj4jAqG",
    apiAccess.ProcessOwner(),
    assignElementToRoleAndDepartmentRules(),
    validate,
    adminController.assignElementToRoleAndDepartment
  )
  .post(
    "/w5EaVda512xJ0Hn",
    apiAccess.ProcessOwner(),
    adminController.listDepartmentsForElementAssignment
  )
  .post(
    "/zsMxCrIkhM2hHku",
    apiAccess.ProcessOwner(),
    adminController.listRolesForElementAssignment
  )
  .post(
    "/hSdRwo4YCbKiYOx",
    apiAccess.ProcessOwner(),
    // viewElementDraftActivityLogRules(),
    // validate,
    adminController.viewElementDraftActivityLog
  )
  .post(
    "/wohSYOxdRKiCb4Y",
    apiAccess.ProcessOwner(),
    viewElementDraftActivityLogHistoryRules(),
    validate,
    adminController.viewElementDraftActivityLogHistory
  )
  .post(
    "/iRSYwKhCo4bOdxw",
    apiAccess.ProcessOwner(),
    impactAnalysisRules(),
    validate,
    adminController.impactAnalysis
  )
  .post(
    "/PsO5MIZrIxZj3By",
    apiAccess.ProcessOwner(),
    formModuleCreateRules(),
    validate,
    adminController.createFormModule
  )
  .post(
    "/uYY8Rc8wsvxZ3tu",
    apiAccess.ProcessOwner(),
    publishFormModuleRules(),
    validate,
    adminController.publishFormModule
  )
  .post(
    "/2SJaQq5bSwRSpjT",
    apiAccess.ProcessOwner(),
    adminController.listFormModule
  )
  .post(
    "/cx9wcqMS8DrEpln",
    apiAccess.ProcessOwner(),
    formDraftViewRules(),
    validate,
    adminController.viewFormModuleDraft
  )
  .post(
    "/xubBhwhWe47521x",
    apiAccess.ProcessOwner(),
    formDraftViewRules(),
    validate,
    adminController.deleteFormModule
  )
  .post(
    "/hwhW7xubB521xe4",
    apiAccess.ProcessOwner(),
    adminController.verifyUserPermissionToEditForm
  )
  .post(
    "/521xxubWe47Bhwh",
    apiAccess.ProcessOwner(),
    createFormRules(),
    validate,
    adminController.createForm
  )
  .post("/52ub471xWexhBhw", viewFormRules(), validate, adminController.viewForm)
  .post(
    "/47Wex2ubBhh5w1x",
    apiAccess.ProcessOwner(),
    createCampaignRules(),
    validate,
    adminController.createCampaign
  )
  .post(
    "/bBWex2uh1x47h5w",
    apiAccess.ProcessOwner(),
    adminController.campaignList
  )
  .post(
    "/Wex2uhh5w1x47bB",
    apiAccess.ProcessOwner(),
    campaignListRules(),
    validate,
    adminController.campaignReportList
  )
  .post(
    "/ex2u5w1x47bBWhh",
    apiAccess.ProcessOwner(),
    exportCampaignExcelRules(),
    validate,
    adminController.exportCampaignExcel
  )
  .post(
    "/u5w7bBhhex2W1x4",
    apiAccess.ProcessOwner(),
    fetchAssignedDataForElementRules(),
    validate,
    adminController.fetchAssignedDataForElement
  )
  .post(
    "/1x4u5w7hhex2WbB",
    apiAccess.ProcessOwner(),
    revokeAssignedUsersFromElementRules(),
    validate,
    adminController.revokeAssignedUsersFromElement
  )
  .post(
    "/hh1x2WbB4u5w7ex",
    apiAccess.ProcessOwner(),
    hideUnhideModuleRules(),
    validate,
    adminController.hideUnhideModule
  )
  .post(
    "/LPXWAQ5Z4ZXKvbT",
    apiAccess.ProcessOwner(),
    adminController.syncModule
  )
  .post(
    "/vbTAQ5LPXWXKZ4Z",
    apiAccess.ProcessOwner(),
    adminController.createFlowWithNormalText
  )
  .post(
    "/KZ4ZvQ5WXbTALPX",
    apiAccess.ProcessOwner(),
    adminController.createGroup
  )
  .post(
    "/ALZvbTAXbTKZ4PX",
    apiAccess.ProcessOwner(),
    adminController.getAllGroups
  )
  .post(
    "/Q5WZZ4PXvTALXbK",
    apiAccess.ProcessOwner(),
    adminController.getGroupById
  )
  .post(
    "/ZvQ5LPXWXbTAKZ4",
    apiAccess.ProcessOwner(),
    adminController.modifyGroup
  )
  .post(
    "/bTKWXZALPX4ZvQ5",
    apiAccess.ProcessOwner(),
    adminController.deleteGroup
  )
  .post(
    "/LQ5ZPX4ZvXZQ5WA",
    apiAccess.ProcessOwner(),
    createRiskRules(),
    validate,
    adminController.createOrUpdateRisk
  )
  .post(
    "/ZQ5PZLQ5X4ZvXWA",
    apiAccess.ProcessOwner(),
    updateRiskRules(),
    validate,
    adminController.updateRiskModule
  )
  .post(
    "/vQALP5bZX4WXZTK",
    apiAccess.ProcessOwner(),
    adminController.fetchAllRiskData
  )
  .post(
    "/P5bvZQALZXTK4WX",
    apiAccess.ProcessOwner(),
    adminController.fetchRiskByIds
  )
  .post(
    "/QZXTK5ALZPbv4WX",
    apiAccess.ProcessOwner(),
    adminController.fetchRiskDashboardData
  )
  .post(
    "/AbZXTLvZQP5K4WX",
    apiAccess.ProcessOwner(),    
    adminController.fetchSopModuleDraftBasedOnRiskSopLink
  ) 
  .post(
    "/XAbTLvZZQ5K4WPX",
    apiAccess.ProcessOwner(),
    adminController.softDeleteRisk
  )
  .post(
    "/bTK4WQLvZZ5XAPX",
    apiAccess.ProcessOwner(),
    adminController.fetchBlankPage
  )
  .post(
    "/WQZPXTK4ZL5XAvb",
    apiAccess.ProcessOwner(),
    adminController.upsertDocumentTemplate
  )
  .post(
    "/ZPWK4ZLQXT5XAvb",
    apiAccess.ProcessOwner(),
    adminController.getDocumentTemplateById
  )
  .post(
    "/XTZPWK4ZL5XAvbQ",
    apiAccess.ProcessOwner(),
    adminController.getTemplateResponse
  )
  .post(
    "/K4ZXXTZPWAL5vbQ",
    apiAccess.ProcessOwner(),
    adminController.getDocumentTemplatesByUser
  )
  .post(
    "/AL5vZPWbK4ZXXTQ",
    apiAccess.ProcessOwner(),
    adminController.deleteDocumentTemplate
  )
  .post(
    "/QXAvK4ZLTXZPW5b",
    apiAccess.ProcessOwner(),
    createOrUpdateTemplateOrBlankDocument
  )

  .post(
    "/mkbvZQALZXTK426",
    apiAccess.ProcessOwner(),
    adminController.saveEmailTemplate
  )
  .post(
    "/ZQALZXTK4Wbv26m",
    apiAccess.ProcessOwner(),
    adminController.getAllEmailTemplates
  )
  .post(
    "/TK4WbvZQALX26mk",
    apiAccess.ProcessOwner(),
    adminController.deleteEmailTemplateById
  
  )
.post(
  "/GT4WbvZQALX26m7",
    apiAccess.ProcessOwner(),
    adminController.getEmailTemplateById
)

.post(
  "/HMTWbvZQALX26gg",
  apiAccess.ProcessOwner(),
  adminController.ConvertDocxToPDF
)
  .post("/AvKQLZP5TXbX4ZW", apiAccess.ProcessOwner(), sendDocumentForReview);
